name: Scrape Latest News

on:
  schedule:
    - cron: "30 * * * *"  # Runs at 30 minutes past the hour
  workflow_dispatch:  # Allows for manual trigger

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraping Script
        run: python scrape_news.py  # Ensure the script name is correct

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git add README.md news_log.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "Update README.md with latest news"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: No Changes Detected
        if: ${{ success() && steps.commit.outputs.changes == '' }}
        run: echo "No updates to README.md. Workflow completed successfully."
      
