name: Scrape Latest News

on:
  schedule:
    - cron: "0 * * * *"  # Every hour at minute 0
  workflow_dispatch:  # Allows for manual trigger

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraping Script
        run: python scrape_news.py  # Ensure the script name is correct

      - name: Commit and Push Changes
        run: |
          git config --global user.name "sh13y"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with latest news"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
